import { expect } from "chai"
import { ethers } from "hardhat"
import * as fs from "fs"
import * as path from "path"

/**
 * Verifies a REAL Groth16 proof on-chain: the fixture is generated by
 * `make zk-setup` (resolver/cmd/zkgen) from the record-commitment circuit
 * and proves that the seeded A-record payload hashes to its on-chain MiMC
 * commitment. The exported Verifier reverts with ProofInvalid() otherwise.
 */
describe("ZKVerifier (gnark Groth16 export)", () => {
	const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, "fixtures", "zkproof.json"), "utf8"))

	async function deployVerifier() {
		const Verifier = await ethers.getContractFactory("Verifier")
		return Verifier.deploy()
	}

	it("accepts a valid record-commitment proof", async () => {
		const verifier = await deployVerifier()
		await expect(verifier.verifyProof(fixture.proofCalldata, [BigInt(fixture.commitmentDec)])).to.not.be.reverted
	})

	it("rejects the proof against a different commitment", async () => {
		const verifier = await deployVerifier()
		await expect(
			verifier.verifyProof(fixture.proofCalldata, [BigInt(fixture.commitmentDec) + 1n]),
		).to.be.revertedWithCustomError(verifier, "ProofInvalid")
	})

	it("rejects a tampered proof", async () => {
		const verifier = await deployVerifier()
		const tampered = ethers.getBytes(fixture.proofCalldata)
		tampered[10] ^= 0xff
		await expect(verifier.verifyProof(tampered, [BigInt(fixture.commitmentDec)])).to.be.reverted // ProofInvalid or point-decoding error
	})

	it("rejects malformed proof lengths", async () => {
		const verifier = await deployVerifier()
		await expect(verifier.verifyProof("0x1234", [BigInt(fixture.commitmentDec)])).to.be.revertedWith(
			"invalid proof length",
		)
	})
})
